### ISSUE TITLE
numberOfInitialTopics > numberOfDocs exception

### ISSUE THREAD

**Issue by arnim** [arnim/HDP#1]
java.lang.ArrayIndexOutOfBoundsException: XXX
    at de.uni_leipzig.informatik.asv.hdp.HDPGibbsSampler.addInstances(HDPGibbsSampler.java:85)
    at de.uni_leipzig.informatik.asv.hdp.HDPGibbsSampler.main(HDPGibbsSampler.java:455)

TODO update the addInstances

**Comment by eisioriginal** [comment]
Sollen wir da mal schauen oder ist das deine interne Notiz

**Comment by arnim** [comment]
Its only a note.. I'll change that
